### ISSUE TITLE
Support some google's ptypes

### ISSUE THREAD

**Issue by ysugimoto** [ysugimoto/grpc-graphql-gateway#15]
## Describe

We'd like to support some google's ptypes like:

- `google.protobuf.Empty`
- `google.protobuf.Timestamp`
- `google.protobuf.Any`
- any others?

## Planning

It feels redundant for me to create GraphQL Type in compilation time, so it should be supplied from this package I think.

```go
import (
    "github.com/ysugimoto/grpc-graphql-gateway/ptypes/empty"
    "github.com/ysugimoto/grpc-graphql-gateway/ptypes/timestamp"
    "github.com/ysugimoto/grpc-graphql-gateway/ptypes/any"
)
```

**Comment by saichander** [comment]
@ysugimoto In the Readme File, it is mentioned that Google Protobuf [Wrapper](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto) Types are not supported. Is this still true? I have seen some changes related to Wrappers' support in the above Pull Request [#19](https://github.com/ysugimoto/grpc-graphql-gateway/pull/19), but it is not working. Do you have plans to support it?

Could you share your findings on the issues that you are running into to support wrapper types?

**Comment by ysugimoto** [comment]
Hi @saichander , yes I'd like to support wrapper types in https://github.com/ysugimoto/grpc-graphql-gateway/blob/master/ptypes/wrappers/wrappers.go of master branch.

but If you could not work using it, could you tell me how error message is? I'll fix them and I want to work correctly even if you are using wrapper types!

**Comment by saichander** [comment]
Hi @ysugimoto  , I am running into the following error while trying to work with `google.protobuf.StringValue` type

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0x135ff25]

goroutine 1 [running]:
github.com/graphql-go/graphql.(*Object).Error(0x0, 0x199eaec, 0x31)
	/Users/saichander/go/pkg/mod/github.com/graphql-go/graphql@v0.7.8/definition.go:462 +0x5
github.com/graphql-go/graphql.defineFieldMap(0x1c14620, 0xc000378370, 0xc00036e0c0, 0x0, 0x6e, 0x6f)
	/Users/saichander/go/pkg/mod/github.com/graphql-go/graphql@v0.7.8/definition.go:519 +0x289
github.com/graphql-go/graphql.(*Object).Fields(0xc000378370, 0x22195b8)
	/Users/saichander/go/pkg/mod/github.com/graphql-go/graphql@v0.7.8/definition.go:433 +0xa5
github.com/graphql-go/graphql.typeMapReducer(0xc0003af7f0, 0xc00036e2d0, 0x1c4bae0, 0xc000378370, 0xc000378370, 0x0, 0x0)
	/Users/saichander/go/pkg/mod/github.com/graphql-go/graphql@v0.7.8/schema.go:337 +0x916
github.com/graphql-go/graphql.typeMapReducer(0xc0003af7f0, 0xc00036e2d0, 0x1c4bae0, 0xc000378420, 0x2, 0xc00037a100, 0x1)
	/Users/saichander/go/pkg/mod/github.com/graphql-go/graphql@v0.7.8/schema.go:348 +0xaab
github.com/graphql-go/graphql.NewSchema(0xc000378420, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/saichander/go/pkg/mod/github.com/graphql-go/graphql@v0.7.8/schema.go:108 +0x83e
github.com/ysugimoto/grpc-graphql-gateway/runtime.(*ServeMux).validateHandler(0xc00036a040, 0x1c3dd20, 0xc00036e060, 0xc000010870, 0xc000010868)
	/Users/saichander/go/pkg/mod/github.com/ysugimoto/grpc-graphql-gateway@v0.18.0/runtime/mux.go:76 +0x12b
github.com/ysugimoto/grpc-graphql-gateway/runtime.(*ServeMux).AddHandler(...)
	/Users/saichander/go/pkg/mod/github.com/ysugimoto/grpc-graphql-gateway@v0.18.0/runtime/mux.go:44
sojern.io/gateway/bookingsreport.RegisterBookingsReportServiceGraphqlHandler(0xc00036a040, 0xc000366380, 0x0, 0x22195b8)
	/Users/saichander/<masked path>/bookingsreport.graphql.go:350 +0x100
main.main()
	/Users/saichander/<masked path>/main.go:36 +0x301
exit status 2`

**Additional Details**
-  protoc        v3.11.4
- github.com/ysugimoto/grpc-graphql-gateway v0.18.0
- go version go1.13.8 darwin/amd64
- Code at line `/Users/saichander/<masked path>/bookingsreport.graphql.go:350` - `return mux.AddHandler(new_graphql_resolver_BookingsReportService(conn))`
- Confirming that everything worked as expected **without** wrapper types.
- wrapper type definition in bookingsreport.graphql.go file - `Type: gql_ptypes_wrappers.Gql__type_StringValue()`

Please let me know if you need additional details for debugging.

**Comment by ysugimoto** [comment]
@saichander Thanks! I look into it and try to fix them.

**Comment by ysugimoto** [comment]
Hi @saichander , I found ridiculous bug which is caused by me X(
Just fixed typo, and it seems to work fine on my environment.

I'll merge and release latest version, so please try it after that, thanks!

**Comment by ysugimoto** [comment]
Just pushed `v0.18.1` 👍

**Comment by saichander** [comment]
@ysugimoto It is working now 😄 . Thanks for fixing it quickly, I truly appreciate it 👍

**Comment by vamshi-tg** [comment]
@ysugimoto looks like some of the new commits after **v0.18.1** broke Google Protobuf Wrappers' support. I'm getting the below error when working with any message from "google/protobuf/wrappers.proto"

`[PROTOC-GEN-GRAPHQL] Error: google's ptype "wrapperspb" does not implement for now.`


protoc-version: 3.14.0
grpc-graphql-gateway v0.19.2

**Comment by ysugimoto** [comment]
@vamshi-tg Hello, I looked into it.

On `master` branch, same as latest/v.019.2, it has been compiled successfully.
Here are my proto file and compiled result: https://gist.github.com/ysugimoto/a03039996edadcf3941d9e31da9ae293

> [PROTOC-GEN-GRAPHQL] Error: google's ptype "wrapperspb" does not implement for now.

Currently, we can support Google's types only `timestamp`, `wrappers`, and `empty`.
The error you got is raised at here: https://github.com/ysugimoto/grpc-graphql-gateway/blob/master/protoc-gen-graphql/spec/field.go#L15-L31 and wrapps.proto is declarated on here: https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/wrappers.proto

It helps me if you could show me your protobuf file that compilation failed, thanks.

**Comment by vamshi-tg** [comment]
@ysugimoto Thanks for your response. Protobuf version 3.14.0 was causing the issue. It worked when compiling using v3.13.0. I checked the protobuf v3.14.0 release notes. There are some changes related **go_package** options for the google.golang.org/protobuf module. This could be the reason for it to not compile with v3.14.0

**Comment by vamshi-tg** [comment]
@ysugimoto, on a side note, though the wrappers are working, empty does not work with protoc v3.13.0 and grpc-graphql-gateway v0.19.2

**playground.proto**
```
import "graphql.proto";
import "google/protobuf/wrappers.proto";
import "google/protobuf/empty.proto";

option go_package = ".;playground";

service Playground {
  option (graphql.service) = {
    host : "localhost:50051"
    insecure : true
  };
  
  rpc Echo(google.protobuf.Empty) returns (EchoResponse) {
    option (graphql.schema) = {
      type : QUERY
      name : "echo"
    };
  }
}

message EchoResponse {
  string reply = 1;
  google.protobuf.Int64Value extra = 2;
}
```

The proto is compilied, but there is an error when running it. Here is the screen shot from the vscode, it looks like it is not being used.
![Screenshot 2021-02-10 at 12 46 48 PM](https://user-images.githubusercontent.com/32225088/107477747-516c7800-6b9e-11eb-8c2e-c6307d92a854.png)

And the actual runtime error message is
```
playground.graphql.go13:2: cannot find package "." in:
	/Workspace/go/vendor/github.com/ysugimoto/grpc-graphql-gateway/ptypes/empty
```

**Comment by ysugimoto** [comment]
@vamshi-tg Thank you for your great information about it 😄 

I didn't notice that the protobuf `v3.14.0` problem because I'm keeping using `v3.13.0` for a long time...
I'll try to compile using `v3.14.0` and tackle to solve this, thanks

**Comment by ysugimoto** [comment]
@vamshi-tg I fixed this problem in PR #36. I appreciate you could try this branch and then I'll publish a new version 👍

**Comment by ysugimoto** [comment]
`v0.20.0` has been published.
